services:
  jacob-weizman-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jacob-weizman-web
    ports:
      - "6343:6343"
    restart: unless-stopped
    labels:
      - "com.jacob-weizman.description=Digital Detox Website"
      - "com.jacob-weizman.version=1.0"
